# Azure Pipeline Configuration for Node.js Azure Function


trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the main branch


pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

variables:
  - group: "prisma"

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
          - task: UseNode@1
            inputs:
              version: '16.x'
            displayName: 'Install Node.js'

          - script: |
              cd js  # Navigate to the JavaScript function directory
              npm install  # Install dependencies
            displayName: 'Install Dependencies and Build'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/js'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp_node.zip'
              replaceExistingArchive: true
            displayName: 'Archive Function App'
            
          
          - task: Bash@3
            displayName: Twistcli
            inputs:
              targetType: 'inline'
              script: |
                curl -k -u $(key):$(secret) -X GET -o twistcli $(address)/api/v1/util/twistcli
                chmod +x twistcli

                ./twistcli serverless scan --user $(key) --password $(secret) --address $(address) $(Build.ArtifactStagingDirectory)/functionapp_node.zip --details

          - publish: $(Build.ArtifactStagingDirectory)/functionapp_node.zip
            artifact: functionapp
            displayName: 'Publish Artifact'

