# This build is used for public PR and CI builds.

trigger:
- main

pool:
  vmImage: ubuntu-latest
 
stages:
  - stage: Build
    jobs:
      - job: Build
        strategy:
          matrix:
            NODE18:
              NODE_VERSION: "18.x"
            NODE20:
              NODE_VERSION: "20.x"
            NODE22:
              NODE_VERSION: "22.x"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: "Install Node.js"
          - script: npm ci
            displayName: "npm ci (ts)"
            workingDirectory: "ts"
          - script: npm run build
            displayName: "npm run build (ts)"
            workingDirectory: "ts"
          - script: npm run lint
            displayName: "npm run lint (ts)"
            workingDirectory: "ts"
          - script: npm ci
            displayName: "npm ci (js)"
            workingDirectory: "js"
          - script: npm run lint
            displayName: "npm run lint (js)"
            workingDirectory: "js"
